// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Service_Management_Service.Data;

#nullable disable

namespace Service_Management_Service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251104190413_InitialServiceTables")]
    partial class InitialServiceTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Service_Management_Service.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppointmentID"));

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CustomerID")
                        .HasColumnType("integer");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("interval");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("VehicleID")
                        .HasColumnType("integer");

                    b.HasKey("AppointmentID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("VehicleID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Service_Management_Service.Models.AppointmentService", b =>
                {
                    b.Property<int>("AppointmentServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppointmentServiceID"));

                    b.Property<int>("AppointmentID")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CustomPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("ServiceID")
                        .HasColumnType("integer");

                    b.HasKey("AppointmentServiceID");

                    b.HasIndex("AppointmentID");

                    b.HasIndex("ServiceID");

                    b.ToTable("AppointmentServices");
                });

            modelBuilder.Entity("Service_Management_Service.Models.Customer", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("integer");

                    b.HasKey("UserID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Service_Management_Service.Models.Employee", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<string>("EmpNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Service_Management_Service.Models.ProjectAppointment", b =>
                {
                    b.Property<int>("AppointmentID")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("text");

                    b.Property<string>("ProjectTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("AppointmentID");

                    b.ToTable("ProjectAppointments");
                });

            modelBuilder.Entity("Service_Management_Service.Models.Service", b =>
                {
                    b.Property<int>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ServiceID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Service_Management_Service.Models.ServiceAppointment", b =>
                {
                    b.Property<int>("AppointmentID")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceOption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ServicePackageID")
                        .HasColumnType("integer");

                    b.HasKey("AppointmentID");

                    b.HasIndex("ServicePackageID");

                    b.ToTable("ServiceAppointments");
                });

            modelBuilder.Entity("Service_Management_Service.Models.ServicePackage", b =>
                {
                    b.Property<int>("ServicePackageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServicePackageID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("ServicePackageID");

                    b.ToTable("ServicePackages");
                });

            modelBuilder.Entity("Service_Management_Service.Models.ServicePackageItem", b =>
                {
                    b.Property<int>("ServicePackageItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServicePackageItemID"));

                    b.Property<int>("ServiceID")
                        .HasColumnType("integer");

                    b.Property<int>("ServicePackageID")
                        .HasColumnType("integer");

                    b.HasKey("ServicePackageItemID");

                    b.HasIndex("ServiceID");

                    b.HasIndex("ServicePackageID");

                    b.ToTable("ServicePackageItems");
                });

            modelBuilder.Entity("Service_Management_Service.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Service_Management_Service.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehicleID"));

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<int>("CustomerID")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VehicleID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Service_Management_Service.Models.Appointment", b =>
                {
                    b.HasOne("Service_Management_Service.Models.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service_Management_Service.Models.Employee", "Employee")
                        .WithMany("AssignedAppointments")
                        .HasForeignKey("EmployeeID");

                    b.HasOne("Service_Management_Service.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Service_Management_Service.Models.AppointmentService", b =>
                {
                    b.HasOne("Service_Management_Service.Models.Appointment", "Appointment")
                        .WithMany("AppointmentServices")
                        .HasForeignKey("AppointmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service_Management_Service.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Service_Management_Service.Models.Customer", b =>
                {
                    b.HasOne("Service_Management_Service.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Service_Management_Service.Models.Employee", b =>
                {
                    b.HasOne("Service_Management_Service.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Service_Management_Service.Models.ProjectAppointment", b =>
                {
                    b.HasOne("Service_Management_Service.Models.Appointment", "Appointment")
                        .WithOne("ProjectDetails")
                        .HasForeignKey("Service_Management_Service.Models.ProjectAppointment", "AppointmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Service_Management_Service.Models.ServiceAppointment", b =>
                {
                    b.HasOne("Service_Management_Service.Models.Appointment", "Appointment")
                        .WithOne("ServiceDetails")
                        .HasForeignKey("Service_Management_Service.Models.ServiceAppointment", "AppointmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service_Management_Service.Models.ServicePackage", "ServicePackage")
                        .WithMany()
                        .HasForeignKey("ServicePackageID");

                    b.Navigation("Appointment");

                    b.Navigation("ServicePackage");
                });

            modelBuilder.Entity("Service_Management_Service.Models.ServicePackageItem", b =>
                {
                    b.HasOne("Service_Management_Service.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service_Management_Service.Models.ServicePackage", "Package")
                        .WithMany("Items")
                        .HasForeignKey("ServicePackageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Service_Management_Service.Models.Vehicle", b =>
                {
                    b.HasOne("Service_Management_Service.Models.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Service_Management_Service.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentServices");

                    b.Navigation("ProjectDetails");

                    b.Navigation("ServiceDetails");
                });

            modelBuilder.Entity("Service_Management_Service.Models.Customer", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Service_Management_Service.Models.Employee", b =>
                {
                    b.Navigation("AssignedAppointments");
                });

            modelBuilder.Entity("Service_Management_Service.Models.ServicePackage", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
