CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Appointments" (
    "AppointmentID" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerID" text NOT NULL,
    "VehicleID" integer NOT NULL,
    "EmployeeID" text,
    "StartDate" timestamp without time zone NOT NULL,
    "Time" interval NOT NULL,
    "EndDate" timestamp without time zone,
    "Status" character varying(50) NOT NULL,
    "AppointmentType" character varying(50) NOT NULL,
    "TotalPrice" numeric(10,2),
    CONSTRAINT "PK_Appointments" PRIMARY KEY ("AppointmentID")
);

CREATE TABLE "Notifications" (
    "NotificationID" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserID" character varying(450) NOT NULL,
    "NotificationType" character varying(50) NOT NULL,
    "Title" character varying(100) NOT NULL,
    "Message" character varying(500) NOT NULL,
    "EntityType" character varying(50),
    "EntityID" integer,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "ReadAt" timestamp without time zone,
    "Metadata" character varying(1000),
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("NotificationID")
);

CREATE INDEX "IX_Notifications_CreatedAt" ON "Notifications" ("CreatedAt");

CREATE INDEX "IX_Notifications_UserID" ON "Notifications" ("UserID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251108041619_InitialCreate', '9.0.10');

COMMIT;

